include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  exclude: [lib/**/*.freezed.dart, lib/**/*.g.dart]
  errors:
    invalid_use_of_visible_for_testing_member: error

linter:
  rules:
    unawaited_futures: false